---
title: "Saviez-vous que..."
weight: 2
header_menu: true
---

Les couches jetables en chiffres 

  - ***5 000*** à ***7 000*** couches jetables sont nécessaire pour rendre un enfant propre
  - ***1*** 500***$ à ***2 500***$ seront nécessaires pour l'achat des couches jetables 
  - ***1*** à ***2*** tonnes de déchets sont créés par bébé, représentant environ ***5*** arbres et ***25kg*** de matière plastique obtenus avec ***67kg*** de pétrole brut
  - ***60 000*** tonnes de couches jetables sont enfouies chaque année au Québec
  - ***300*** à ***500*** ans sont nécessaires pour la biodégradation d'une seule couche jetable

---

Les couches lavables en chiffres

  - ***30*** couches lavables suffisent à rendre un enfant propre
  - ***1 080***$ à ***1 200***$ seront investis chez LPF, et les couches pourront servir pour les frères et soeurs
  - ***200*** à ***300*** utilisations par couche avant de pouvoir devenir un chiffon, puis d'être jetées
  - ***6*** mois sont nécessaires pour la biodégradation d'une seule couche lavable

---

Bienfaits des couches lavables

  - Facile d’utilisation et d’entretien
  - Ajustement facile, de la naissance à deux ans, à l’aide de boutons-pression évolutifs
  - Mince et absorbantes 
  - Protège la peau des bébé de l'humidité, réduisant l'érythème fessier
  - Lavables à la machine 
  - Esthétisme 
  - Écologiques 
  - Douces et confortables

